name: mongo-sharding

services:
  configSrv:
    image: mongo:latest
    container_name: configSrv
    restart: always
    ports:
      - '27019:27019'
    volumes:
      - config-data:/data/db
    command:
      [
        'mongod',
        '--configsvr',
        '--replSet',
        'config_server',
        '--bind_ip_all',
        '--port',
        '27019',
      ]
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--eval',
          "db.adminCommand('ping')",
          '--port',
          '27019',
        ]
      interval: 5s
      start_period: 10s

  shard1:
    image: mongo:latest
    container_name: shard1
    restart: always
    ports:
      - '27018:27018'
    volumes:
      - shard1-data:/data/db
    command:
      [
        'mongod',
        '--shardsvr',
        '--replSet',
        'shard1',
        '--bind_ip_all',
        '--port',
        '27018',
      ]
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--eval',
          "db.adminCommand('ping')",
          '--port',
          '27018',
        ]
      interval: 5s
      start_period: 10s

  shard2:
    image: mongo:latest
    container_name: shard2
    restart: always
    ports:
      - '27020:27020'
    volumes:
      - shard2-data:/data/db
    command:
      [
        'mongod',
        '--shardsvr',
        '--replSet',
        'shard2',
        '--bind_ip_all',
        '--port',
        '27020',
      ]
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--eval',
          "db.adminCommand('ping')",
          '--port',
          '27020',
        ]
      interval: 5s
      start_period: 10s

  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - router-data:/data/db
    depends_on:
      - shard1
      - shard2
      - configSrv
    command:
      [
        'mongos',
        '--configdb',
        'config_server/configSrv:27019',
        '--bind_ip_all',
        '--port',
        '27017',
      ]
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--eval',
          "db.adminCommand('ping')",
          '--port',
          '27017',
        ]
      interval: 5s
      start_period: 10s

  pymongo_api_sharding:
    container_name: pymongo_api_sharding
    build:
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: 'mongodb://mongos_router:27017'
      MONGODB_DATABASE_NAME: 'somedb'

volumes:
  config-data:
  shard1-data:
  shard2-data:
  router-data:
